### ISSUE TITLE
Generated "spec file for package FOO" comment has incorrect package name

### ISSUE THREAD

**Issue by peti** [openSUSE/obs-service-format_spec_file#17]
I committed a spec file update that didn't touch the initial comment section, but according to https://build.opensuse.org/package/rdiff/devel:languages:haskell:lts:7/ghc-yaml?linkrev=base&rev=2 the commit ended up modifying that comment after all, and the generated comment has the package name wrong. I assume that `obs-service-format_spec` is responsible for that change? Would it be possible to fix the script not to mis-detected that package name?

**Comment by DimStar77** [comment]
/usr/lib/obs/service/format_spec_file.files/prepare_spec stumbles over the fact that the Name: tag in the .spec file contains a variable:

```
%global pkg_name yaml
%bcond_with tests
Name:           ghc-%{pkg_name}
```

```
if ( ! stat ((glob("$specdir/$base_package*.spec"))[0] || "") ) {
  $base_package =~ s/[0-9]$//;
}

if ( ! stat ((glob("$specdir/$base_package*.spec"))[0] || "") ) {
  $base_package =~ s/\-[^\-]*$//;
}
```
as the file ghc-%{pkg_name}.spec does not exist it strips it to some 'better guess'

**Comment by peti** [comment]
Ping? This bug is messing up all our carefully generated spec files and I'm wondering whether is going to be fixed?

**Comment by dcermak** [comment]
This issue is still present. I've just experienced it with vagrant-sshfs: https://build.opensuse.org/request/show/733756, where I (or obs-service-format_spec to be more precise) changed the header from `# spec file for package vagrant-sshfs` to `# spec file for package vagrant`.

For this package the name field is only a macro:
```
Name:           %{vagrant_plugin_name}
```
so not sure where the service gets the guess from.

Changing the name to
```
Name:           vagrant-sshfs
```
works around this issue.

**Comment by bugfinder** [comment]
see https://github.com/openSUSE/obs-service-format_spec_file/pull/38
(underlying problem was that the parser has looked for %define for a long time but ignored %global,
which has probably also existed for long but the use came into habit more recently ...)

having said that: "Name:" is the line in the specfile that defines the macro "%name", personally I think the benefit of another macro on top of that is limited ...

**Comment by dcermak** [comment]
> having said that: "Name:" is the line in the specfile that defines the macro "%name", personally I think the benefit of another macro on top of that is limited ...

The macro `%{vagrant_plugin_name}` is used by a bunch of other macros in that spec. For `vagrant-sshfs` the package name is equal to the value of `%{vagrant_plugin_name}`, that's why removed this duplication, but I see your point.

**Comment by peti** [comment]
> "Name:" is the line in the specfile that defines the macro "%name", personally I think the benefit of another macro on top of that is limited ...

I think there *is*  some benefit to distinguishing `ghc-mtl` (`%name`) and `mtl`, which is the actual name of the package. The same goes for Python packages, R packages, etc. Many ecosystems are using a name prefix that obfuscates how the package is actually called inside of that ecosystem.
