### ISSUE TITLE
comment moved wrongly

### ISSUE THREAD

**Issue by pgajdos** [openSUSE/obs-service-format_spec_file#19]
As can be seen in current libpng16 submission (sr#436546), comment is moved somewhere else, which is not acceptable (in my opinion, comments should not be moved at all). Unfortunately I cannot submit correct version, as format_spec_file prevents it.
`
-Group:          System/Libraries
 # bug437293
+Group:          System/Libraries
 %ifarch ppc64
 Obsoletes:      libpng-64bit
 %endif
`

**Comment by scarabeusiv** [comment]
I suppose it is caused by 89e01afb2947fed8d71f02eee9a5d871cd7e4160

**Comment by hwoarang** [comment]
Quite possibly yes. I believe that the optimal solution would be to never mess with the comments at all. I will have a look

**Comment by hwoarang** [comment]
Right so I don't think my commit broke it per se. The code would have re-arranged the Group field anyway. The problem is that format_spec_file re-arranges the License and Group fields but it does not take the comments around these fields into consideration so they end up all over the place. The fix is not terribly complicated but it makes the code somewhat ugly. I will post a PR soon.

**Comment by aaronpuchert** [comment]
I have been running into this recently, see the most recent [changes to llvm9](https://build.opensuse.org/package/rdiff/devel:tools:compiler/llvm9?linkrev=base&rev=33). Would be nice if you could fix this.

**Comment by coolo** [comment]
https://github.com/openSUSE/obs-service-format_spec_file/pull/42 refactors the tool - and will do a little less for the sake of not breaking things
